//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentRent
    {
        public int Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Address { get; set; }
        public int Company_Phone_Number { get; set; }
        public string Others { get; set; }
    }
}
