//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renovation
    {
        public int Id { get; set; }
        public string ClientAddress { get; set; }
        public System.DateTime Startdate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Price { get; set; }
        public int Area { get; set; }
        public string Decription { get; set; }
    }
}
